services:
  WebApp:
    image: webapp
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - Database
  
  Database:
    image: postgres:latest
    environment:
      POSTGRES_DB: Database
      POSTGRES_USER: User
      POSTGRES_PASSWORD: qwe123asd
    ports:
      - "5432:5432"